version = 1

; Global defaults applied to all models
[*]
n-gpu-layers = auto
flash-attn = true
jinja = true
cache-ram = 8192
models-max = 1

[Qwen2.5-7B-Instruct-Q4_K_M]
model = /models/Qwen2.5-7B-Instruct-Q4_K_M.gguf
chat-template-file = /app/templates/Qwen-Qwen2.5-7B-Instruct.jinja
ctx-size = 32768

[Gemma-3-4B-Q4_K_M]
model = /models/gemma-3-4b-it-Q4_K_M.gguf
ctx-size = 131072

[GPT-OSS-20B-Q4_K_M]
model = /models/gpt-oss-20b-Q4_K_M.gguf
chat-template-file = /app/templates/openai-gpt-oss-120b.jinja
ctx-size = 131072
